### ISSUE TITLE
Text is missing on Flathub.org?

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/io.liri.Text#1]
The Text page is missing on the Flathub website. It looks like that there is some issue with the AppStream metadata.
![captura de tela de 2018-09-07 19-53-55](https://user-images.githubusercontent.com/26097419/45246460-ca818a00-b2d7-11e8-8c03-984b7d9e9e33.png)

**Comment by plfiorini** [comment]
I'm updating appdata

**Comment by plfiorini** [comment]
New version with updated appdata is up but I still see the page broken.

**Comment by plfiorini** [comment]
Don't know how long does it take but the web site to update metadata, but GNOME Software shows the latest update correctly.

![screenshot from 2018-10-19 08-33-23](https://user-images.githubusercontent.com/843710/47201379-e28a0600-d379-11e8-9807-05f3f999c810.png)

AppStream metadata is fine: https://github.com/lirios/text/blob/develop/data/io.liri.Text.appdata.xml

Could be a Flathub bug.

**Comment by plfiorini** [comment]
Will wait a few more hours and if the web site keep saying 'App not found' I will file a bug over there.

**Comment by l-n-s** [comment]
running `appstream-util validate` against your manifest gives this 

```
io.liri.Text.appdata.xml: FAILED:
• tag-missing           : <translation> not specified
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/lirios/text/develop/.project/screenshots/text1.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/lirios/text/develop/.project/screenshots/text1.png]
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/lirios/text/develop/.project/screenshots/text2.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/lirios/text/develop/.project/screenshots/text2.png]
• style-invalid         : <p> is too short [Add missing summary to appdata file.]
Validation of files failed

```

**Comment by plfiorini** [comment]
That command is too strict and doesn't mean much. Metadata is valid, it passed Flathub CI.
Try this command on your system on other apps and see for yourself, a lot of them will fail with that command and yet they are shown:

```sh
find ~/.local/share/flatpak/app -type f  -name "*.appdata.xml" | xargs appstream-util validate | grep FAILED
```

**Comment by l-n-s** [comment]
idk dude, just saying. maybe that's why it fails to display at flathub.org, maybe not

**Comment by TingPing** [comment]
> it passed Flathub CI.

If Flathub CI was useful for validating appdata we wouldn't be here. All it does is ensure your app-id is correct basically.

**Comment by plfiorini** [comment]
The only error that Calculator doesn't have is that short `<p>` and that is easy to change.
I noticed that the translation tag is optional (see https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html) and yet `appstream-util validate` fails.
I'll just get all complains fixed and add validation to our CI (that is validate not validate-relax).

**Comment by jgarciao** [comment]
I'm sorry, I saw this bug randomly last month, add a bookmark in my browser to take a look and totally forgot until today that I bump into the link

This looks like a bug in the website's backend (see related bug). I'll try to fix it next weekend

Sorry for the inconvenience

**Comment by jgarciao** [comment]
I found the solution yesterday. When we update the website backend in production (probably tomorrow) the information will be properly shown in the website. I'm sorry it took so long

**Comment by jgarciao** [comment]
Yesterday we published a new version of the website backend that fixes the problem

The app is published now: https://flathub.org/apps/details/io.liri.Text

**Comment by plfiorini** [comment]
Thanks @jgarciao

**Comment by jgarciao** [comment]
Your welcome. I'm sorry it took so long to fix it
